// BLUEFOR loadouts

omtk_il_set_loadout_bluefor_B_officer_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Squadleader";(_this select 0) addHeadgear "rhsusf_patrolcap_ocp";(_this select 0) addBackpack "tf_rt1523g_rhs";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_ACOG3";[(_this select 0),1,"rhsusf_mag_7x45acp_MHP"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhsusf_weap_m1911a1";(_this select 0) addWeapon "Binocular";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;[(_this select 0),2,"rhsusf_mag_7x45acp_MHP"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_MapTools"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_Soldier_SL_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Squadleader";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "tf_rt1523g_rhs";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_ACOG3";[(_this select 0),1,"rhsusf_mag_7x45acp_MHP"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhsusf_weap_m1911a1";(_this select 0) addWeapon "Binocular";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;[(_this select 0),2,"rhsusf_mag_7x45acp_MHP"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_MapTools"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_Soldier_TL_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Teamleader";(_this select 0) addHeadgear "rhsusf_ach_helmet_ess_ocp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_m4a1_m320";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_ACOG3";(_this select 0) addWeapon "Binocular";[(_this select 0),4,"rhs_mag_M441_HE"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_mag_M433_HEDP"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_mag_m662_red"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_medic_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Medic";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),40,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),15,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),15,"ACE_epinephrine"] call omtk_fnc_addItem;[(_this select 0),5,"ACE_bloodIV"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;[(_this select 0),2,"SmokeShell"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_Soldier_GL_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Grenadier";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_m4a1_m320";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),4,"rhs_mag_M441_HE"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_mag_M433_HEDP"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_mag_m662_red"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_Soldier_A_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Rifleman";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),1,"rhs_m136_hedp_mag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_M136_hedp";[(_this select 0),4,"rhs_mag_M441_HE"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_mag_M433_HEDP"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_mag_m662_red"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_soldier_AR_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ucp_SAW";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";
[(_this select 0),1,"rhsusf_100Rnd_556x45_soft_pouch"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m249_pip_elcan";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),5,"rhsusf_100Rnd_556x45_soft_pouch"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_soldier_AAR_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Rifleman";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),1,"rhs_m136_hedp_mag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_M136_hedp";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;[(_this select 0),4,"rhsusf_100Rnd_556x45_soft_pouch"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_support_GMG_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ucp_SAW";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";
[(_this select 0),1,"rhsusf_100Rnd_762x51"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m240B";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_ELCAN";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),4,"rhsusf_100Rnd_762x51"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_support_AMG_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Rifleman";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),7,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;[(_this select 0),4,"rhsusf_100Rnd_762x51"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_soldier_AT_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ucp_SAW";(_this select 0) addHeadgear "rhsusf_ach_helmet_headset_ess_ocp";(_this select 0) addBackpack "B_Carryall_cbr";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),1,"tf47_m3maaws_HEAT"] call omtk_fnc_addItem;(_this select 0) addWeapon "tf47_m3maaws";(_this select 0) addSecondaryWeaponItem "tf47_optic_m3maaws";[(_this select 0),1,"tf47_m3maaws_HEAT"] call omtk_fnc_addItem;[(_this select 0),2,"tf47_m3maaws_HEDP"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_soldier_AAT_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Rifleman";(_this select 0) addHeadgear "rhsusf_ach_helmet_ESS_ucp";(_this select 0) addBackpack "B_Carryall_cbr";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),1,"rhs_m136_mag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_M136";[(_this select 0),2,"tf47_m3maaws_HEAT"] call omtk_fnc_addItem;[(_this select 0),1,"tf47_m3maaws_HEDP"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_soldier_LAT_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ucp_SAW";(_this select 0) addHeadgear "rhsusf_ach_helmet_headset_ess_ocp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),1,"rhs_m136_mag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_M136";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_soldier_unarmed_f = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ucp_SAW";(_this select 0) addHeadgear "rhsusf_ach_helmet_headset_ess_ocp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),1,"rhs_m136_hedp_mag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_M136";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_soldier_M_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Rifleman";(_this select 0) addHeadgear "rhs_Booniehat_ocp";(_this select 0) setFace "WhiteHead_22_a";
[(_this select 0),1,"rhsusf_20Rnd_762x51_m118_special_Mag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m14ebrri";(_this select 0) addPrimaryWeaponItem "optic_DMS";(_this select 0) addWeapon "ACE_Vector";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhsusf_20Rnd_762x51_m118_special_Mag"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_RangeCard"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_Kestrel4500"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_ATragMX"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_sniper_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Rifleman";(_this select 0) addHeadgear "rhs_Booniehat_ocp";(_this select 0) setFace "WhiteHead_22_a";
[(_this select 0),1,"rhsusf_5Rnd_300winmag_xm2010"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_XM2010";(_this select 0) addPrimaryWeaponItem "optic_LRPS";(_this select 0) addWeapon "ACE_Vector";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),11,"rhsusf_5Rnd_300winmag_xm2010"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_RangeCard"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_Kestrel4500"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_ATragMX"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_spotter_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Rifleman";(_this select 0) addHeadgear "rhs_Booniehat_ocp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";(_this select 0) setFace "WhiteHead_22_a";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_ACOG";(_this select 0) addWeapon "ACE_Vector";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_RangeCard"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_Kestrel4500"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_ATragMX"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_soldier_exp_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Rifleman";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_DefusalKit"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_Clacker"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_M26_Clacker"] call omtk_fnc_addItem;[(_this select 0),2,"SatchelCharge_Remote_Mag"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_Soldier_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Rifleman";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),11,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_m67"] call omtk_fnc_addItem;[(_this select 0),1,"SmokeShell"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_diver_TL_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp";(_this select 0) addHeadgear "rhsusf_cvc_helmet";
[(_this select 0),1,"rhsusf_mag_7x45acp_MHP"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhsusf_weap_m1911a1";(_this select 0) addWeapon "Binocular";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),2,"rhsusf_mag_7x45acp_MHP"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_MapTools"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_crew_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp";(_this select 0) addHeadgear "rhsusf_cvc_helmet";
[(_this select 0),1,"rhsusf_mag_7x45acp_MHP"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhsusf_weap_m1911a1";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),2,"rhsusf_mag_7x45acp_MHP"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_Helipilot_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addHeadgear "H_PilotHelmetHeli_B";
[(_this select 0),1,"rhsusf_mag_7x45acp_MHP"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhsusf_weap_m1911a1";(_this select 0) addWeapon "Binocular";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),2,"rhsusf_mag_7x45acp_MHP"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_MapTools"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_helicrew_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addHeadgear "H_PilotHelmetHeli_B";
[(_this select 0),1,"rhsusf_mag_7x45acp_MHP"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhsusf_weap_m1911a1";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),2,"rhsusf_mag_7x45acp_MHP"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_soldier_UAV_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Teamleader";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "B_MAV_B_BACKPACK";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";(_this select 0) addWeapon "Binocular";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_MapTools"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_recon_JTAC_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Teamleader";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "tf_rt1523g_rhs";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),19,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_recon_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Rifleman";(_this select 0) addHeadgear "rhs_Booniehat_ocp";(_this select 0) addBackpack "rhsusf_assault_eagleaiii_ocp";(_this select 0) setFace "WhiteHead_22_a";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_ACOG3";(_this select 0) addWeapon "ACE_Yardage450";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_MapTools"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_recon_LAT_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Rifleman";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "RHS_M2_Gun_Bag";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_bluefor_B_Recon_Sharpshooter_F = {
(_this select 0) forceAddUniform "rhs_uniform_cu_ocp";(_this select 0) addVest "rhsusf_iotv_ocp_Rifleman";(_this select 0) addHeadgear "rhsusf_ach_helmet_ucp";(_this select 0) addBackpack "RHS_M2_Tripod_Bag";
[(_this select 0),1,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_m4a1_grip";(_this select 0) addPrimaryWeaponItem "rhsusf_acc_compm4";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;
};


// REDFOR loadouts

omtk_il_set_loadout_redfor_O_officer_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_officer";(_this select 0) addHeadgear "rhs_beret_vdv2";(_this select 0) addBackpack "tf_mr3000_multicam";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_1p29";[(_this select 0),1,"rhs_mag_9x18_12_57N181S"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_makarov_pmm";(_this select 0) addWeapon "Binocular";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),2,"rhs_mag_9x18_12_57N181S"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_MapTools"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_Soldier_SL_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_officer";(_this select 0) addHeadgear "rhs_fieldcap_khk";(_this select 0) addBackpack "tf_mr3000_multicam";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_1p29";[(_this select 0),1,"rhs_mag_9x18_12_57N181S"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_makarov_pmm";(_this select 0) addWeapon "Binocular";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),2,"rhs_mag_9x18_12_57N181S"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_MapTools"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_Soldier_TL_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "rhs_sidor";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m_gp25";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";(_this select 0) addWeapon "Binocular";[(_this select 0),4,"rhs_VOG25"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_VOG25P"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_GRD40_White"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_GRD40_Green"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_GRD40_Red"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_medic_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_medic";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "rhs_sidor";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),40,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),15,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),15,"ACE_epinephrine"] call omtk_fnc_addItem;[(_this select 0),5,"ACE_bloodIV"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_Soldier_GL_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "rhs_sidor";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m_gp25";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),4,"rhs_VOG25"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_VOG25P"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_GRD40_White"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_GRD40_Green"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_GRD40_Red"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_Soldier_A_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "rhs_sidor";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),1,"rhs_rshg2_mag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_rshg2";[(_this select 0),4,"rhs_VOG25"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_VOG25P"] call omtk_fnc_addItem;[(_this select 0),4,"rhs_GRD40_White"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),7,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_Soldier_AR_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "rhs_sidor";
[(_this select 0),1,"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M"] call omtk_fnc_addItem;(_this select 0) addWeapon "CUP_arifle_RPK74M";(_this select 0) addPrimaryWeaponItem "CUP_optic_Kobra";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_Soldier_AAR_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "rhs_sidor";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),5,"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),7,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_support_GMG_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "rhs_sidor";
[(_this select 0),1,"rhs_100Rnd_762x54mmR"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_pkp";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),4,"rhs_100Rnd_762x54mmR"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_support_AMG_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "rhs_sidor";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),3,"rhs_100Rnd_762x54mmR"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),7,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_Soldier_AT_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m_ess";(_this select 0) addBackpack "rhs_rpg_empty";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),1,"rhs_rpg7_PG7VL_mag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_rpg7";(_this select 0) addSecondaryWeaponItem "rhs_acc_pgo7v";[(_this select 0),1,"rhs_rpg7_PG7VR_mag"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_rpg7_PG7VL_mag"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_rpg7_OG7V_mag"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),7,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_Soldier_AAT_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "rhs_rpg_empty";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),1,"rhs_rpg26_mag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_rpg26";[(_this select 0),1,"rhs_rpg7_PG7VR_mag"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_rpg7_PG7VL_mag"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_rpg7_OG7V_mag"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),7,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_Soldier_LAT_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m_ess";(_this select 0) addBackpack "rhs_sidor";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),1,"rhs_rpg26_mag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_rpg26";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_Soldier_unarmed_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m_ess";(_this select 0) addBackpack "rhs_sidor";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),1,"rhs_rshg2_mag"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_rshg2";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_soldier_M_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_sniper";(_this select 0) addHeadgear "CUP_H_RUS_Bandana_HS";(_this select 0) setFace "GreekHead_A3_10_a";
[(_this select 0),1,"rhs_10Rnd_762x54mmR_7N1"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_svds_pso1";(_this select 0) addPrimaryWeaponItem "rhs_acc_pso1m2";(_this select 0) addWeapon "lerca_1200_black";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),11,"rhs_10Rnd_762x54mmR_7N1"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_RangeCard"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_Kestrel4500"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_ATragMX"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_sniper_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_sniper";(_this select 0) addHeadgear "CUP_H_RUS_Bandana_HS";(_this select 0) setFace "GreekHead_A3_10_a";
[(_this select 0),1,"rhs_10Rnd_762x54mmR_7N1"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_svds_pso1";(_this select 0) addPrimaryWeaponItem "rhs_acc_pso1m2";(_this select 0) addWeapon "lerca_1200_black";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),11,"rhs_10Rnd_762x54mmR_7N1"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_RangeCard"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_Kestrel4500"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_ATragMX"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_spotter_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_sniper";(_this select 0) addHeadgear "CUP_H_RUS_Bandana_HS";(_this select 0) addBackpack "rhs_sidor";(_this select 0) setFace "GreekHead_A3_10_a";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";(_this select 0) addWeapon "lerca_1200_black";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_mag_30Rnd_556x45_M855A1_Stanag"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_soldier_exp_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "rhs_sidor";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),2,"SatchelCharge_Remote_Mag"] call omtk_fnc_addItem;[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_DefusalKit"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_Clacker"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_M26_Clacker"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_Soldier_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "rhs_sidor";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),13,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_diver_TL_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_officer";(_this select 0) addHeadgear "rhs_tsh4_ess";
[(_this select 0),1,"rhs_mag_9x18_12_57N181S"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_makarov_pmm";(_this select 0) addWeapon "Binocular";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),2,"rhs_mag_9x18_12_57N181S"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_MapTools"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_crew_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addHeadgear "rhs_tsh4_ess";
[(_this select 0),1,"rhs_mag_9x18_12_57N181S"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_makarov_pmm";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),2,"rhs_mag_9x18_12_57N181S"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_helipilot_F = {
(_this select 0) forceAddUniform "rhs_uniform_df15";(_this select 0) addHeadgear "rhs_zsh7a_mike";
[(_this select 0),1,"rhs_mag_9x18_12_57N181S"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_makarov_pmm";(_this select 0) addWeapon "Binocular";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),2,"rhs_mag_9x18_12_57N181S"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_MapTools"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_helicrew_F = {
(_this select 0) forceAddUniform "rhs_uniform_df15";(_this select 0) addHeadgear "rhs_zsh7a_mike";
[(_this select 0),1,"rhs_mag_9x18_12_57N181S"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_makarov_pmm";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),2,"rhs_mag_9x18_12_57N181S"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_soldier_UAV_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "B_MAV_B_BACKPACK";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";(_this select 0) addWeapon "Binocular";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),7,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_MapTools"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_recon_JTAC_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "tf_mr3000_multicam";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_recon_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "CUP_H_RUS_Bandana_HS";(_this select 0) addBackpack "rhs_sidor";(_this select 0) setFace "GreekHead_A3_10_a";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";(_this select 0) addWeapon "ACE_Yardage450";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),2,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_MapTools"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_microDAGR"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_recon_LAT_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "RHS_Kord_Gun_Bag";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;
};

omtk_il_set_loadout_redfor_O_Pathfinder_F = {
(_this select 0) forceAddUniform "rhs_uniform_gorka_r_g";(_this select 0) addVest "rhsgref_6b23_khaki_rifleman";(_this select 0) addHeadgear "rhs_6b7_1m";(_this select 0) addBackpack "RHS_Kord_Tripod_Bag";
[(_this select 0),1,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;(_this select 0) addWeapon "rhs_weap_ak74m";(_this select 0) addPrimaryWeaponItem "rhs_acc_ekp1";[(_this select 0),6,"ACE_fieldDressing"] call omtk_fnc_addItem;[(_this select 0),2,"ACE_morphine"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rgd5"] call omtk_fnc_addItem;[(_this select 0),1,"rhs_mag_rdg2_white"] call omtk_fnc_addItem;[(_this select 0),1,"ACE_EarPlugs"] call omtk_fnc_addItem;(_this select 0) linkItem "ItemMap";(_this select 0) linkItem "ItemCompass";(_this select 0) linkItem "ItemRadio";(_this select 0) linkItem "tf_microdagr";[(_this select 0),9,"rhs_30Rnd_545x39_7N10_AK"] call omtk_fnc_addItem;
};

